info:
  app:
    name: Naked Wines Website
    description: This is a service mocking the naked wines website
    version: 1.0.0

spring:
  application:
    name: web

server:
  port: 8080

zuul:
  routes:
    customers: /customers/**